version: '3.8'
services:
  postgres:
    container_name: eleicao_db
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: 'UTC'
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - eleicao_net

networks:
  eleicao_net:
    name: eleicao_net

volumes:
  postgres_db:
